# [begin] zplug
export ZPLUG_HOME=$(brew --prefix)/opt/zplug
source $ZPLUG_HOME/init.zsh

# コマンドのハイライト
zplug "zsh-users/zsh-syntax-highlighting"
# 履歴を遡りやすくする
zplug "zsh-users/zsh-history-substring-search"
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "chrissicool/zsh-256color"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
# [end] zplug


# [begin] go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
# [end] go

# [begin] fzf + ghq
function ghq-fzf() {
  local src=$(ghq list | fzf --preview "ls -laTp $(ghq root)/{} | tail -n+4 | awk '{print \$9\"/\"\$6\"/\"\$7 \" \" \$10}'")
  if [ -n "$src" ]; then
    BUFFER="cd $(ghq root)/$src"
    zle accept-line
  fi
  zle -R -c
}
zle -N ghq-fzf
bindkey '^g' ghq-fzf
# [end] fzf + ghq

# [begin] alias
# exa
if [[ $(command -v exa) ]]; then
  alias ls='exa --icons --git'
  alias lt='exa -T -L 3 -a -I "node_modules|.git|.cache" --icons'
fi
# nvim
if [[ $(command -v nvim) ]]; then
  alias vim='nvim'
fi
# bat
if [[ $(command -v bat) ]]; then
  alias cat='bat'
fi
# [end] alias

# Starshipの初期化。
# 必ずファイルの最後で読み込む
eval "$(starship init zsh)"
